blueprintapp/blueprints/people/models.py
from blueprintapp.app import db


class Person(db.Model):
    __tablename__ = 'people'

    pid = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    age = db.Column(db.Integer, nullable=False)
    job = db.Column(db.String(100), nullable=False)

    def __repr__(self):
        return f'<Person {self.name} - Age: {self.age}>'
    
    def get_id(self):
        return self.pid

blueprintapp/blueprints/people/routes.py
from flask import Flask, Blueprint, render_template, request, redirect, url_for
from blueprintapp.app import db
from blueprintapp.blueprints.people.models import Person

people = Blueprint('people', __name__, template_folder='templates')

@people.route('/')
def index():
    people = Person.query.all()
    return render_template('people/index.html', people=people)

@people.route('/create', methods=['GET', 'POST'])
def create():
    if request.method == 'GET':
        return render_template('people/create.html')
    elif request.method == 'POST':
        name = request.form.get('name')
        age = int(request.form.get('age'))
        job = request.form.get('job')
        
        new_person = Person(name=name, age=age, job=job)
        db.session.add(new_person)
        db.session.commit()
        
        return redirect(url_for('people.index'))

blueprintapp/blueprints/people/templates/people/create.html
{% extends "base.html" %}
{% block title %}Create Person{% endblock %}
{% block content %}
<h1>Create Person</h1>
<form action="{{ url_for('people.create')}}" method="post">
    <label for="name">Name:</label>
    <input type="text" name="name" required>
    <label for="job">Job:</label>
    <input name="job"></input>
    <label for="age">Age:</label>
    <input type="number" name="age"></input>
    <button type="submit">Create</button>
</form>
{% endblock %}

blueprintapp/blueprints/people/templates/people/index.html
{% extends "base.html" %}
{% block title %}People{% endblock %}
{% block content %}
    <ul>
        {% for person in people %}
            <li>
                {{ person }}
            </li>
        {% endfor %}
    </ul>
        <a href="{{ url_for('core.index') }}">Home</a>
    <a href="{{ url_for('people.create') }}">Create</a>
{% endblock %}