blueprintapp/blueprints/todos/models.py
from blueprintapp.app import db


class Todo(db.Model):
    __tablename__ = 'todos'

    tid = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    description = db.Column(db.String(100))
    done = db.Column(db.Boolean, default=False)

    def __repr__(self):
        return f'<Todo {self.title} - Completed: {self.done}>'
    
    def get_id(self):
        return self.tid

blueprintapp/blueprints/todos/routes.py
from flask import Flask, Blueprint, render_template, request, redirect, url_for
from blueprintapp.app import db
from blueprintapp.blueprints.todos.models import Todo

todos = Blueprint('todos', __name__, template_folder='templates')

@todos.route('/')
def index():
    todos = Todo.query.all()
    return render_template('todos/index.html', todos=todos)

@todos.route('/create', methods=['GET', 'POST'])
def create():
    if request.method == 'GET':
        return render_template('todos/create.html')
    elif request.method == 'POST':
        title = request.form.get('title')
        description = request.form.get('description')
        done = True if request.form.get('done') else False
        
        new_todo = Todo(title=title, description=description, done=done)
        db.session.add(new_todo)
        db.session.commit()
        
        return redirect(url_for('todos.index'))

blueprintapp/blueprints/todos/templates/todos/create.html
{% extends "base.html" %}
{% block title %}My Web Page{% endblock %}
{% block content %}
<h1>Create Todo</h1>
<form action="{{ url_for('todos.create')}}" method="post">
    <label for="title">Title:</label>
    <input type="text" name="title" required>
    <label for="description">Description:</label>
    <textarea name="description"></textarea>
    <input type="checkbox" name="done"> Done
    <button type="submit">Create</button>
</form>
{% endblock %}

blueprintapp/blueprints/todos/templates/todos/index.html
{% extends "base.html" %}
{% block title %}My Web Page{% endblock %}
{% block content %}
    <ul>
        {% for todo in todos %}
            <li>
                {{ todo }}
            </li>
        {% endfor %}
    </ul>
    <a href="{{ url_for('core.index') }}">Home</a>
    <a href="{{ url_for('todos.create') }}">Create</a>
{% endblock %}